eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
server.port: 9010
cartapp.uri: http://cart-service/cart/getAllCartItems/
inventory.uri: http://inventory-service/inventory/

spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams:
  binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  bindings.input.consumer.application-id: order-service
spring.cloud.stream.bindings.output:
  destination: order_topic
spring.cloud.stream.bindings.input:
  destination: cart_topic

spring.cloud.stream.bindings.payment.destination: payment_topic
spring.cloud.stream.bindings.payment_status.destination: payment_status_topic
spring.cloud.stream.bindings.cart.destination: cart_remove_topic
            
            